import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import NavBar from "@/components/NavBar";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import UserSync from "@/components/userSync";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="flex items-start justify-between min-h-screen text-black!"
        suppressHydrationWarning
      >
        <ClerkProvider>
          <ConvexClientProvider>
            <UserSync fallback={null}>
              <SideBar />
              <main className="flex-1">
                <NavBar />
                {children}
              </main>
            </UserSync>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
